import { join } from 'node:path';
import { readFileContent, ensureDir, writeFileContent } from '../utils/fs.js';
import { parseYaml, stringifyYaml } from '../utils/yaml.js';
import { renderTemplate } from '../utils/template.js';
import type { Contract, ContractModel, ContractModelField, ContractRoute } from '../core/types.js';

interface OpenAPISpec {
  openapi?: string;
  info?: { title?: string; description?: string };
  paths?: Record<string, Record<string, { summary?: string; description?: string }>>;
  components?: {
    schemas?: Record<string, {
      type?: string;
      properties?: Record<string, { type?: string; description?: string }>;
      required?: string[];
    }>;
  };
}

export async function importOpenAPI(specPath: string, skillsDir: string): Promise<string[]> {
  const content = await readFileContent(specPath);
  const spec = parseYaml<OpenAPISpec>(content);
  const created: string[] = [];

  // Extract models from components/schemas
  const models: ContractModel[] = [];
  if (spec.components?.schemas) {
    for (const [name, schema] of Object.entries(spec.components.schemas)) {
      if (schema.type === 'object' && schema.properties) {
        const fields: ContractModelField[] = [];
        for (const [fieldName, fieldDef] of Object.entries(schema.properties)) {
          fields.push({
            name: fieldName,
            type: fieldDef.type ?? 'unknown',
            required: schema.required?.includes(fieldName) ?? false,
            description: fieldDef.description,
          });
        }
        models.push({ name, fields });
      }
    }
  }

  // Extract routes from paths
  const routes: ContractRoute[] = [];
  if (spec.paths) {
    for (const [path, methods] of Object.entries(spec.paths)) {
      for (const [method, details] of Object.entries(methods)) {
        if (['get', 'post', 'put', 'delete', 'patch'].includes(method.toLowerCase())) {
          routes.push({
            method: method.toUpperCase(),
            path,
            description: details.summary ?? details.description,
          });
        }
      }
    }
  }

  // Group routes by first path segment as domain
  const domainRoutes = new Map<string, ContractRoute[]>();
  for (const route of routes) {
    const segments = route.path.split('/').filter(Boolean);
    const domain = segments[0] ?? 'api';
    const existing = domainRoutes.get(domain) ?? [];
    existing.push(route);
    domainRoutes.set(domain, existing);
  }

  // Create a skill for each domain
  for (const [domain, domainRouteList] of domainRoutes) {
    const skillDir = join(skillsDir, domain);
    await ensureDir(skillDir);

    const today = new Date().toISOString().split('T')[0];
    const skillContent = await renderTemplate('skill.md.hbs', {
      name: domain,
      description: `API domain: ${domain} (imported from OpenAPI spec)`,
      domain,
      lastVerified: today,
    });

    const header = `<!-- Generated by DomainKit from OpenAPI spec -->\n\n`;
    await writeFileContent(join(skillDir, 'SKILL.md'), header + skillContent);

    // Create contract
    const contract: Contract = {
      models: models.filter(m => {
        // Heuristic: assign models that might relate to this domain
        return m.name.toLowerCase().includes(domain.toLowerCase());
      }),
      api: { routes: domainRouteList },
    };

    const refsDir = join(skillDir, 'references');
    await ensureDir(refsDir);
    await writeFileContent(join(refsDir, 'contract.yaml'), stringifyYaml(contract));

    created.push(domain);
  }

  return created;
}
