import { join } from 'node:path';
import { renderTemplate } from '../utils/template.js';
import { writeFileContent, ensureDir } from '../utils/fs.js';
import { stringifyYaml } from '../utils/yaml.js';
import type { DiscoveredModule } from './module-scanner.js';
import type { PersonaDefinition } from '../personas/types.js';

export interface GenerateOptions {
  module: DiscoveredModule;
  skillsDir: string;
  withContract: boolean;
  persona?: PersonaDefinition;
}

export async function generateSkillDraft(options: GenerateOptions): Promise<void> {
  const { module: mod, skillsDir, withContract, persona } = options;
  const skillDir = join(skillsDir, mod.name);
  const today = new Date().toISOString().split('T')[0];

  await ensureDir(skillDir);

  let templateName = 'skill.md.hbs';
  let templateData: Record<string, unknown> = {
    name: mod.name,
    description: `Domain skill for the ${mod.name} module`,
    domain: mod.name,
    codePaths: `${mod.path}/**`,
    lastVerified: today,
  };

  if (persona) {
    // Check if a dedicated persona template exists, otherwise use composite
    const dedicatedTemplate = `personas/${persona.id}.skill.md.hbs`;
    const compositeTemplate = 'personas/composite.skill.md.hbs';

    // If persona id contains '+' it's a merged persona — use composite
    if (persona.id.includes('+')) {
      templateName = compositeTemplate;
      templateData = { ...templateData, personaId: persona.id, sections: persona.sections };
    } else {
      templateName = dedicatedTemplate;
    }
  }

  const skillContent = await renderTemplate(templateName, templateData);

  const header = `<!-- Generated by DomainKit -->\n<!-- TODO: Review and customize this draft -->\n\n`;
  await writeFileContent(join(skillDir, 'SKILL.md'), header + skillContent);

  if (withContract) {
    const contractContent = await renderTemplate('contract.yaml.hbs', {
      name: mod.name,
    });
    const refsDir = join(skillDir, 'references');
    await ensureDir(refsDir);
    await writeFileContent(join(refsDir, 'contract.yaml'), contractContent);
  }
}
