import { join } from 'node:path';
import { renderTemplate } from '../utils/template.js';
import { writeFileContent, ensureDir } from '../utils/fs.js';
import { stringifyYaml } from '../utils/yaml.js';
import type { DiscoveredModule } from './module-scanner.js';

export interface GenerateOptions {
  module: DiscoveredModule;
  skillsDir: string;
  withContract: boolean;
}

export async function generateSkillDraft(options: GenerateOptions): Promise<void> {
  const { module: mod, skillsDir, withContract } = options;
  const skillDir = join(skillsDir, mod.name);
  const today = new Date().toISOString().split('T')[0];

  await ensureDir(skillDir);

  const skillContent = await renderTemplate('skill.md', {
    name: mod.name,
    description: `Domain skill for the ${mod.name} module`,
    domain: mod.name,
    codePaths: `${mod.path}/**`,
    lastVerified: today,
  });

  const header = `<!-- Generated by DomainKit -->\n<!-- TODO: Review and customize this draft -->\n\n`;
  await writeFileContent(join(skillDir, 'SKILL.md'), header + skillContent);

  if (withContract) {
    const contractContent = await renderTemplate('contract.yaml', {
      name: mod.name,
    });
    const refsDir = join(skillDir, 'references');
    await ensureDir(refsDir);
    await writeFileContent(join(refsDir, 'contract.yaml'), contractContent);
  }
}
